[package]
name = "rust-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
chrono = "0.4.39"
env_logger = "0.11.6"
futures = "0.3.31"
futures-util = "0.3.31"
mongodb = "3.1.1"
num_cpus = "1.16.0"
serde = "1.0.216"
