services:
  rustapp:
    container_name: rustapp
    image: rust-server:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: {}
